version: '3.3'

volumes:
    dbdata:

services:
  mysql:
    platform: linux/amd64
    image: mysql
    container_name: mentornaut-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mentornaut
      MYSQL_USER: mentornaut
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
  php:
    container_name: mentornaut-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html:cached
      - ./var:/var/www/html/var:delegated
      - ./vendor:/var/www/html/vendor:delegated
    tty: true
